Adding validate command
fsaintjacques/semver-tool pull request #62
Opened 2021-12-23 20:39 UTC by mymasse

Fixes: #61

2021-12-24 13:22 UTC, ranger6 requested changes
See comments on two sections.

2021-12-24 13:22 UTC, ranger6 commented on test/semver.bats
> +@test "valid semver in validate" {
Seems a bit light for the tests.  I'd add maybe one or two with more complex values and certainly the error cases: i.e. wrong number of arguments (none, one, three).

2021-12-24 13:27 UTC, mymasse commented on test/semver.bats
> +@test "valid semver in validate" {
Will do.

2021-12-24 13:28 UTC, mymasse commented on src/semver
> +function command_validate {
So @fsaintjacques in the issue I raised suggested we use error status for this command, see issue #61

2021-12-24 14:24 UTC, ranger6 commented on src/semver
> +function command_validate {
Yes, @fsaintjacques did suggest this.  So, we either have different opinions and/or we have missed something.  I think he missed the fact that using the exit status hides true error conditions :-)  And, in the example usage, directing stderr to /dev/null makes it worse.  So, we'll wait for him to check in!

2021-12-24 17:45 UTC, fsaintjacques commented on src/semver
> +function command_validate {
I'm torn between preserving consistency with the existing patterns and more natural integration with shell scripting primitives. This sub-command is precisely made to be used in scripting conditionals, hence I would find it more natural to use the exit code at the expense of consistency and exceptionally catching errors.

If we go the consistency route, then the caller will always have to capture stdout in a variable and then use the conditional, *but* that's the interface which we expose with compare.

I have no strong opinion on the mater, let's go for consistency.

2021-12-24 19:22 UTC, mymasse commented on src/semver
> +function command_validate {
I'll make the changes after Christmas

2021-12-27 17:49 UTC, ranger6 commented on src/semver
> +function command_validate {
Just a reminder: with this change, we should move to version 3.3.0.  This means the new version needs to be put in the source (and the tests? .. not sure).  With this, when the PR is done, we can squash-merge-tag .. bingo!

2022-01-12 19:58 UTC, mymasse commented on test/semver.bats
> +@test "valid semver in validate" {
More test added

2022-01-12 19:58 UTC, mymasse commented on src/semver
> +function command_validate {
Command refactored to return: valid or invalid.

2022-01-14 09:23 UTC, ranger6 commented on src/semver
> +function command_validate {
Looks good!

Only thing missing is the new version of semver.  Should move to 3.3.0 (as noted above) as the API changes in a backwards compatible manner.  After the PR is merged, we should publish this as a release.

2022-01-14 12:34 UTC, mymasse commented on src/semver
> +function command_validate {
Sorry missed that, wasn't to sure if I needed to do anything, bump the version in the file.

2022-01-14 12:52 UTC, ranger6 commented
+1

2022-01-14 13:51 UTC, fsaintjacques approved these changes

2022-01-14 13:51 UTC, fsaintjacques commented on README.md
> +            invalid. See <version> definition.
```suggestion
  validate  Validate if <version> follows the SEMVER pattern (see <version>
            definition). Print 'valid' to stdout if the version is valid, otherwise
            print 'invalid'.
```

2022-01-14 13:51 UTC, fsaintjacques commented on src/semver
> +            invalid. See <version> definition.
```suggestion
  validate  Validate if <version> follows the SEMVER pattern (see <version>
            definition). Print 'valid' to stdout if the version is valid, otherwise
            print 'invalid'.
```

2022-01-14 13:52 UTC, merged

2022-01-14 17:26 UTC, mymasse commented
@ranger6 @fsaintjacques is a github release going to be cut with this? We use semver in one of our Dockerfile and it would be nice to use a github release or tag to detect changes instead of relying on the master branch.

2022-01-14 17:44 UTC, fsaintjacques commented
Voilà.

2022-01-14 17:45 UTC, ranger6 commented
I suggested this in one of my comments.  So, for me, the answer is yes.

I’d be glad to do the mechanics (if there is no objection?).  Otherwise, I’ll let our owner have the pleasure.

> On 14 Jan 2022, at 18:26, Mathieu Massé ***@***.*** ***@***.***>> wrote:
> 
> 
> @ranger6 <https://github.com/ranger6> @fsaintjacques <https://github.com/fsaintjacques> is a github release going to be cut with this? We use semver in one of our Dockerfile and it would be nice to use a github release or tag to detect changes instead of relying on the master branch.
> 
> —
> Reply to this email directly, view it on GitHub <https://github.com/fsaintjacques/semver-tool/pull/62#issuecomment-1013315368>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AA2YZ6JRHKC6OBH72D3ED6DUWBMD3ANCNFSM5KVOZO7Q>.
> Triage notifications on the go with GitHub Mobile for iOS <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675> or Android <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>. 
> You are receiving this because you were mentioned.
>

2022-01-14 17:47 UTC, ranger6 commented
Overtaken by the speed of the internet (and M. Saint-Jacques).

> On 14 Jan 2022, at 18:45, François Saint-Jacques ***@***.*** ***@***.***>> wrote:
> 
> 
> Voilà.
> 
> —
> Reply to this email directly, view it on GitHub <https://github.com/fsaintjacques/semver-tool/pull/62#issuecomment-1013328585>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AA2YZ6PJJPYXYFDNK2JRJGLUWBOKBANCNFSM5KVOZO7Q>.
> Triage notifications on the go with GitHub Mobile for iOS <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675> or Android <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>. 
> You are receiving this because you were mentioned.
>